### ISSUE TITLE
add github pic linking to github

### ISSUE THREAD

**Issue by cfuendev** [cfuendesign/googol#2]
fetch the data from https://api.github.com/users/cfuendesign and retrieve the `avatar_url` property to mimic Google's own avatar that displays user's Google account avatar if he's logged in.

![image](https://user-images.githubusercontent.com/65634520/184755642-e64b3073-bf91-4d68-9a2c-0e5f77f05c29.png)

- [x] Add Picture fetched from GitHub
- [x] Remove CSS for Login Button (button#login)

**Comment by cfuendesign** [comment]
I did not remove the login button's css but commented it instead. I kinda like it and I think it'd be useful for future Google recreation projects. I'll keep it in the css bundle until I find where to store it.

Everything else was solved accordingly!

**Comment by cfuendev** [comment]
I did not remove the login button's css but commented it instead. I kinda like it and I think it'd be useful for future Google recreation projects. I'll keep it in the css bundle until I find where to store it.

Everything else was solved accordingly!
